### ISSUE TITLE
training weight 

### ISSUE THREAD

**Issue by maiminh1996** [robmarkcole/kaggle-ships-in-satellite-imagery-with-YOLOv8#2]
Hello @robmarkcole,

Thank you for repo! It help me so much!

But I want to ask if you can public any checkpoint of your training?

Best regards, 
Nguyen

**Comment by robmarkcole** [comment]
@maiminh1996 see https://github.com/robmarkcole/kaggle-ships-in-satellite-imagery-with-YOLOv8/tree/main/models
